from django.db import models
from Maestro.models import *
from Anexos.models import *
from .choices import *

# Create your models here.
class Liquidacione(models.Model):
    numero = models.CharField(max_length=10)
    clientes = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=True, blank=True)
    id_cobro = models.IntegerField(default=0)
    id_mes = models.IntegerField(default=0)
    id_ano = models.IntegerField(default=0)
    fecha = models.DateTimeField()
    fecha_factura = models.DateTimeField()
    desde = models.DateTimeField()
    hasta = models.DateTimeField()
    id_status = models.CharField(max_length=50, default=0, choices=Status_Auditoria)
    dias = models.IntegerField(default=0)
    nro_maquinas = models.IntegerField(default=0)
    entrada = models.FloatField()
    salida = models.FloatField()
    premios = models.FloatField()
    jack_pot = models.FloatField()
    billeteros = models.FloatField()
    jugadas = models.FloatField()
    neto = models.FloatField()
    pay_back = models.FloatField()
    porcentaje = models.FloatField()
    impuesto = models.FloatField()
    iva = models.FloatField()
    otros = models.FloatField()
    monto = models.FloatField()
    monto_igg = models.FloatField()
    eliminar = models.IntegerField(default=0)
    descuentos = models.FloatField()
    monto_girar = models.FloatField()
    razon = models.ForeignKey(Razos_Social, on_delete=models.CASCADE, null=True, verbose_name="Razon Social")
    impuesto_pendiente = models.FloatField()
    iva_pendiente = models.FloatField()
    otros_pendiente = models.FloatField()
    saldo_pendiente = models.FloatField()
    saldo_favor = models.FloatField()
    descuentos_pendiente = models.FloatField()
    fecha_email = models.DateTimeField()
    pendiente = models.IntegerField(default=0)
    sin_transmitir = models.IntegerField(default=0)
    monto_sin_transmitir = models.FloatField()
    monto_soporte = models.FloatField()
    neto_mes = models.FloatField()
    ingreso = models.FloatField()
    ingreso_mes = models.FloatField()
    tipo = models.CharField(max_length=2)
    dias_liquidar = models.IntegerField(default=0)
    desbalance = models.FloatField(default=0)
    suma_impuestos = models.FloatField(default=0)
    create_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado")
    update_at = models.DateTimeField(auto_now=True, verbose_name="Editado")

class Notificacion(models.Model):
    numero = models.CharField(max_length=10)
    clientes = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=True, blank=True)
    razon = models.ForeignKey(Razos_Social, on_delete=models.CASCADE, null=True, blank=True)
    id_status = models.IntegerField(default=0, choices=Status_Auditoria)
    fecha = models.DateTimeField()
    asunto = models.CharField(max_length=50)
    texto = models.CharField(max_length=500)
    eliminar = models.IntegerField(default=0, null=True)
    fecha_notificacion = models.DateTimeField()

class Cargacsv(models.Model):
    message_id = models.TextField(max_length=50)
    venue_ho_id = models.IntegerField(default=0)
    bar_position = models.IntegerField(default=0)
    create_date = models.DateTimeField()
    transaction_date = models.DateTimeField()
    total_plays = models.FloatField(default=0)
    total_coin_in = models.FloatField(default=0)
    total_coin_out = models.FloatField(default=0)
    total_in = models.FloatField(default=0)
    total_out = models.FloatField(default=0)
    jackpot = models.FloatField(default=0)
    content_id = models.FloatField(default=0)
    create_at = models.DateTimeField(auto_now_add=True, verbose_name="Creado")
    update_at = models.DateTimeField(auto_now=True, verbose_name="Editado")