# Generated by Django 3.2.8 on 2022-03-01 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Maestro', '0001_initial'),
        ('Anexos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargacsv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.TextField(max_length=50)),
                ('venue_ho_id', models.IntegerField(default=0)),
                ('bar_position', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField()),
                ('transaction_date', models.DateTimeField()),
                ('total_plays', models.FloatField(default=0)),
                ('total_coin_in', models.FloatField(default=0)),
                ('total_coin_out', models.FloatField(default=0)),
                ('total_in', models.FloatField(default=0)),
                ('total_out', models.FloatField(default=0)),
                ('jackpot', models.FloatField(default=0)),
                ('content_id', models.FloatField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Editado')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('id_status', models.IntegerField(choices=[('C', 'CALCULADA'), ('R', 'REVISADA'), ('E', 'ENVIADA'), ('C', 'CERRADA')], default=0)),
                ('fecha', models.DateTimeField()),
                ('asunto', models.CharField(max_length=50)),
                ('texto', models.CharField(max_length=500)),
                ('eliminar', models.IntegerField(default=0, null=True)),
                ('fecha_notificacion', models.DateTimeField()),
                ('clientes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.cliente')),
                ('razon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.razos_social')),
            ],
        ),
        migrations.CreateModel(
            name='Liquidacione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('id_cobro', models.IntegerField(default=0)),
                ('id_mes', models.IntegerField(default=0)),
                ('id_ano', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField()),
                ('fecha_factura', models.DateTimeField()),
                ('desde', models.DateTimeField()),
                ('hasta', models.DateTimeField()),
                ('id_status', models.IntegerField(choices=[('C', 'CALCULADA'), ('R', 'REVISADA'), ('E', 'ENVIADA'), ('C', 'CERRADA')], default=0)),
                ('dias', models.IntegerField(default=0)),
                ('nro_maquinas', models.IntegerField(default=0)),
                ('entrada', models.FloatField()),
                ('salida', models.FloatField()),
                ('premios', models.FloatField()),
                ('jack_pot', models.FloatField()),
                ('billeteros', models.FloatField()),
                ('jugadas', models.FloatField()),
                ('neto', models.FloatField()),
                ('pay_back', models.FloatField()),
                ('porcentaje', models.FloatField()),
                ('impuesto', models.FloatField()),
                ('iva', models.FloatField()),
                ('otros', models.FloatField()),
                ('monto', models.FloatField()),
                ('monto_igg', models.FloatField()),
                ('eliminar', models.IntegerField(default=0)),
                ('descuentos', models.FloatField()),
                ('monto_girar', models.FloatField()),
                ('impuesto_pendiente', models.FloatField()),
                ('iva_pendiente', models.FloatField()),
                ('otros_pendiente', models.FloatField()),
                ('saldo_pendiente', models.FloatField()),
                ('saldo_favor', models.FloatField()),
                ('descuentos_pendiente', models.FloatField()),
                ('fecha_email', models.DateTimeField()),
                ('pendiente', models.IntegerField(default=0)),
                ('sin_transmitir', models.IntegerField(default=0)),
                ('monto_sin_transmitir', models.FloatField()),
                ('monto_soporte', models.FloatField()),
                ('neto_mes', models.FloatField()),
                ('ingreso', models.FloatField()),
                ('ingreso_mes', models.FloatField()),
                ('tipo', models.CharField(max_length=2)),
                ('dias_liquidar', models.IntegerField(default=0)),
                ('desbalance', models.FloatField(default=0)),
                ('suma_impuestos', models.FloatField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Editado')),
                ('clientes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.cliente')),
                ('razon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.razos_social', verbose_name='Razon Social')),
            ],
        ),
    ]
