# Generated by Django 3.2.8 on 2022-03-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacione',
            name='id_status',
            field=models.CharField(choices=[('C', 'CALCULADA'), ('R', 'REVISADA'), ('E', 'ENVIADA'), ('C', 'CERRADA')], default=0, max_length=50),
        ),
    ]
