# Generated by Django 3.2.8 on 2022-03-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='liquida',
            field=models.CharField(choices=[('ULT. DIA DELMES', 'ULT. DIA DELMES'), ('1RO MES SIGUIENTE', '1RO MES SIGUIENTE'), ('FECHAS ALEATORIAS', 'FECHAS ALEATORIAS')], default='ULT. DIA DELMES', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='liquida_mes',
            field=models.CharField(choices=[('MENSUAL', 'MENSUAL'), ('RANGO DE FECHA', 'RANGO DE FECHA')], default='MENSUAL', max_length=50, null=True, verbose_name='Metodo'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='id_tipo',
            field=models.IntegerField(choices=[('MENSUAL', 'MENSUAL'), ('RANGO DE FECHA', 'RANGO DE FECHA')], null=True, verbose_name='Metodo:'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='liquida',
            field=models.IntegerField(choices=[('ULT. DIA DELMES', 'ULT. DIA DELMES'), ('1RO MES SIGUIENTE', '1RO MES SIGUIENTE'), ('FECHAS ALEATORIAS', 'FECHAS ALEATORIAS')], default=0, null=True, verbose_name='Cierre Liquidacion:'),
        ),
    ]
