# Generated by Django 3.2.8 on 2022-03-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0002_auto_20220303_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='id_tipo',
            field=models.CharField(choices=[('MENSUAL', 'MENSUAL'), ('RANGO DE FECHA', 'RANGO DE FECHA')], max_length=20, null=True, verbose_name='Metodo:'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='liquida',
            field=models.CharField(choices=[('ULT. DIA DELMES', 'ULT. DIA DELMES'), ('1RO MES SIGUIENTE', '1RO MES SIGUIENTE'), ('FECHAS ALEATORIAS', 'FECHAS ALEATORIAS')], default=0, max_length=20, null=True, verbose_name='Cierre Liquidacion:'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='nombre',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
    ]
