# Generated by Django 3.2.8 on 2022-03-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maestro', '0003_auto_20220309_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='activo',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='dia_liquida',
            field=models.CharField(blank=True, default=30, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='dias_liquida',
            field=models.IntegerField(default=30, null=True, verbose_name='Días Liquidar/Mes:'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='domingo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='email2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='email3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='email_fallas',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Fallas'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='email_recaudo',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Recaudo Diario'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='email_sin_transmitir',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Sin Transm. Semana'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='email_sin_transmitir_dia',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Sin Transm. Dia'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='fecha_liquida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='festivos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='hora_liquida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='liquida',
            field=models.CharField(choices=[('ULT. DIA DELMES', 'ULT. DIA DELMES'), ('1RO MES SIGUIENTE', '1RO MES SIGUIENTE'), ('FECHAS ALEATORIAS', 'FECHAS ALEATORIAS')], max_length=20, null=True, verbose_name='Cierre Liquidacion:'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='reporte',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Incluir Reportes'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='tipo_liquida',
            field=models.IntegerField(default=0, null=True, verbose_name='Tiene Liq. / Cobro Fijo:'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='variable',
            field=models.FloatField(blank=True, default=12, null=True, verbose_name='%Variable'),
        ),
    ]
