# Generated by Django 3.2.8 on 2022-03-01 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Maestro', '0001_initial'),
        ('Anexos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('partes', models.CharField(max_length=100)),
                ('id_status', models.IntegerField(choices=[('PENDIENTE', 'PENDIENTE'), ('EN PROCESO', 'EN PROCESO'), ('CERRADA', 'CERRADA')], default=50)),
                ('fecha', models.DateTimeField()),
                ('fecha_visita', models.DateTimeField()),
                ('fecha_final', models.DateTimeField()),
                ('observacion', models.IntegerField(default=0)),
                ('eliminar', models.IntegerField(default=0)),
                ('id_falla', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Editado')),
                ('clientes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.cliente')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.tecnico')),
            ],
        ),
        migrations.CreateModel(
            name='Reparaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('id_status', models.IntegerField(choices=[('RECIBIDO', 'RECIBIDO'), ('EN REVISION', 'EN REVISION'), ('CERRADA', 'CERRADA')], default=50)),
                ('fecha', models.DateTimeField()),
                ('fecha_recibido', models.DateTimeField()),
                ('fecha_final', models.DateTimeField()),
                ('observacion', models.CharField(max_length=100)),
                ('eliminar', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Editado')),
                ('clientes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.cliente')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.tecnico')),
            ],
        ),
        migrations.CreateModel(
            name='Remisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('contacto', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('id_status', models.IntegerField(choices=[('ABIERTA', 'ABIERTA'), ('CERRADA', 'CERRADA')], default=50)),
                ('fecha', models.DateTimeField()),
                ('fecha_envio', models.DateTimeField()),
                ('fecha_recibido', models.DateTimeField()),
                ('guia', models.CharField(max_length=30)),
                ('observacion', models.CharField(max_length=100)),
                ('eliminar', models.IntegerField(default=0)),
                ('elaborado', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Editado')),
                ('clientes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.cliente')),
                ('id_transporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.transporte')),
            ],
        ),
        migrations.CreateModel(
            name='Falla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('reportado', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('descripcion_igg', models.CharField(max_length=100)),
                ('apagada', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(null=True)),
                ('fecha_solucion', models.DateTimeField(null=True)),
                ('id_status', models.IntegerField(choices=[('PENDIENTE', 'Pendiente'), ('ATENDIDA', 'Atendida'), ('INSPIRED', 'Inspired'), ('SOLUCIONADA', 'Solucionada')], default=0)),
                ('observacion', models.CharField(max_length=100)),
                ('eliminar', models.IntegerField(default=0)),
                ('email', models.IntegerField(default=0)),
                ('email_igg', models.IntegerField(default=0)),
                ('id_seguridad', models.IntegerField(default=0)),
                ('fecha_seguridad', models.DateTimeField(null=True)),
                ('sincroniza', models.IntegerField(default=0)),
                ('fecha_sincroniza', models.DateTimeField()),
                ('telefono', models.CharField(max_length=50)),
                ('prioridad', models.IntegerField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default=50)),
                ('atencion', models.IntegerField(choices=[('NIVEL 1 - TECNICO LOCAL DE SALA', 'NIVEL 1 - TECNICO LOCAL DE SALA'), ('NIVEL 2 - SOPORTE REMOTO', 'NIVEL 2 - SOPORTE REMOTO'), ('NIVEL 3 - TECNICO PMV ENVIADO', 'NIVEL 3 - TECNICO PMV ENVIADO')], default=50)),
                ('resuelto', models.CharField(choices=[('SOPORTE SPOT GAMING', 'SOPORTE SPOT GAMING'), ('SOPORTE INSPIRED', 'SOPORTE INSPIRED')], max_length=50)),
                ('fecha_parcial', models.DateTimeField()),
                ('fecha_atencion', models.DateTimeField(null=True)),
                ('fecha_reopen', models.DateTimeField(null=True)),
                ('fecha_escalado', models.DateTimeField(null=True)),
                ('email_igg2', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Editado')),
                ('clientes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.cliente')),
                ('id_causa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.causasfalla')),
                ('id_error', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.codigofalla')),
                ('id_solucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.solucionfalla')),
                ('juego', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.juego')),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.maquina')),
                ('salas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.sala')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.tecnico')),
            ],
        ),
    ]
