# Generated by Django 3.2.8 on 2022-03-01 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Anexos', '0001_initial'),
        ('Maestro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Importaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Editado')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('id_declaracion', models.IntegerField(default=0)),
                ('descripcion', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100, null=True)),
                ('id_status', models.IntegerField(choices=[('B', 'EN BODEGA'), ('E', 'ENTREGADO')], default=50)),
                ('estado', models.IntegerField(choices=[('B', 'BUENO'), ('M', 'MALO')], default=50)),
                ('fecha_despacho', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('serial', models.CharField(max_length=30)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Editado')),
                ('clientes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.cliente')),
                ('piezas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Anexos.pieza')),
            ],
        ),
        migrations.CreateModel(
            name='Declaracione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('id_status', models.IntegerField(default=0)),
                ('id_ano', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField()),
                ('fecha_factura', models.DateTimeField()),
                ('fecha_recibido', models.DateTimeField()),
                ('observacion', models.CharField(max_length=100)),
                ('eliminar', models.IntegerField()),
                ('id_seguridad', models.IntegerField(default=0)),
                ('fecha_seguridad', models.DateTimeField()),
                ('factura', models.CharField(max_length=20)),
                ('referencia', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Editado')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Maestro.proveedore')),
            ],
        ),
    ]
